### ISSUE TITLE
The composer installation method isn't mentioned on extensions.typo3.org

### ISSUE THREAD

**Issue by DanielFlaum** [internetgalerie/ig_slug#12]
On https://extensions.typo3.org/extension/ig_slug/, under the heading Installation, the Composer `require` command isn't mentioned. Contrast this with https://extensions.typo3.org/extension/slug/, where a Composer `require` command is displayed.

Adding this extension's `require` command to its page on extensions.typo3.org will make it easier for users to install the extension.

**Comment by internetgalerie** [comment]
done
