### ISSUE TITLE
Wrong adding to palettes in Configuration/TCA/Overrides/pages.php

### ISSUE THREAD

**Issue by Kephson** [internetgalerie/ig_slug#2]
Hello,
the adding to palettes in Configuration/TCA/Overrides/pages.php should be done like this:
`\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addFieldsToPalette('pages','title','slug_locked','after:slug');`

Attached you will find the changes in the pages.php file.
Please correct this behaviour, because there are problems with other extensions changing the palette 'title' or 'titleonly'.
Thank you very much.

[pages.zip](https://github.com/internetgalerie/ig_slug/files/2998500/pages.zip)

**Comment by internetgalerie** [comment]
Hello
Your changes have been applied.
Thank you for your input

**Comment by Kephson** [comment]
Thank you very much.
Do you upload it to TYPO3 TER?
You could link your github repo on extensions.typo3.org
