### ISSUE TITLE
Allow nav_title to be used as slug?

### ISSUE THREAD

**Issue by woodyc79** [internetgalerie/ig_slug#33]
Hello! Would it be possible to also have the pages field "nav_title" to be used as basis for the slug?

We have some pages where the nav_title is set and we'd like to have this instead of the title...?

Thank you!

**Comment by wazum** [comment]
¥ou can configure that
https://docs.typo3.org/m/typo3/reference-tca/main/en-us/ColumnsConfig/Type/Slug/Properties/GeneratorOptions.html
